---
- hosts: "{{ hosts }}"
  vars:
    traefik_dir: "~/"
  collections:
    - community.docker

  tasks:
    - name: destroy docker-compose project
      community.docker.docker_compose_v2:
        project_src: "{{ traefik_dir }}traefik"
        files:
          - docker-compose.yaml
        state: absent
        remove_orphans: true
        remove_volumes: true
